### ISSUE TITLE
BUILTIN CD - Read 8

### ISSUE THREAD

**Issue by razorbarbeuk** [Krystalz42/42sh#47]
=================================================================
==4233==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x611000006078 at pc 0x000103707371 bp 0x7fff5c52e090 sp 0x7fff5c52e088
READ of size 8 at 0x611000006078 thread T0
    #0 0x103707370 in refresh_varenv builtin_refresh.c:43
    #1 0x1037050dc in builtin_cd builtin_cd.c:88
    #2 0x1036f4c15 in check_if_builtin check_if_builtins.c:45
    #3 0x1036f980d in op_execution op_execution.c:48
    #4 0x1036f4d74 in execute_node executing_node.c:20
    #5 0x1036d20cd in shell shell.c:35
    #6 0x1036d1d23 in main main.c:23
    #7 0x7fffc3ffe234 in start (libdyld.dylib:x86_64+0x5234)

0x611000006078 is located 8 bytes to the left of 240-byte region [0x611000006080,0x611000006170)
allocated by thread T0 here:
    #0 0x10389bffc in wrap_malloc (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x55ffc)
    #1 0x10371fa84 in ft_memalloc ft_memalloc.c:19
    #2 0x103717bcd in remove_environment remove_environment.c:23
    #3 0x103706da0 in builtin_unsetenv builtin_unsetenv.c:21
    #4 0x1036f4c15 in check_if_builtin check_if_builtins.c:45
    #5 0x1036f980d in op_execution op_execution.c:48
    #6 0x1036f4d74 in execute_node executing_node.c:20
    #7 0x1036d20cd in shell shell.c:35
    #8 0x1036d1d23 in main main.c:23
    #9 0x7fffc3ffe234 in start (libdyld.dylib:x86_64+0x5234)

SUMMARY: AddressSanitizer: heap-buffer-overflow builtin_refresh.c:43 in refresh_varenv
Shadow bytes around the buggy address:
  0x1c2200000bb0: fd fd fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c2200000bc0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x1c2200000bd0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x1c2200000be0: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x1c2200000bf0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
=>0x1c2200000c00: fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa[fa]
  0x1c2200000c10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c2200000c20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 fa fa
  0x1c2200000c30: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x1c2200000c40: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x1c2200000c50: fd fd fd fd fd fd fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==4233==ABORTING
[1]    4233 abort      ./42sh

**Comment by razorbarbeuk** [comment]
Ok
