### ISSUE TITLE
Viol

### ISSUE THREAD

**Issue by jle-quel** [Krystalz42/42sh#69]
Cmd: `press space then tab to launch the completion, up arrow to go in history`
Result:
```
    #0 0x1013a2634 in change_element move_vertical.c:28
    #1 0x1013a255c in move_vertical move_vertical.c:48
    #2 0x1013a0268 in key_arrow_up key_arrow.c:66
    #3 0x10139dab4 in inline_other read_stdin.c:76
    #4 0x10139d9b9 in read_stdin read_stdin.c:93
    #5 0x10139d760 in shell shell.c:28
    #6 0x10139d6fb in main main.c:29
```

**Comment by alexandre-roulin** [comment]
Je vais te violer toi et tes \n
@jle-quel
