### ISSUE TITLE
Viol le retour [FUCKYOU]

### ISSUE THREAD

**Issue by jle-quel** [Krystalz42/42sh#72]
```
    #0 0x107b5480d in create_jobs new_jobs.c:22
    #1 0x107b5478b in new_jobs new_jobs.c:40
    #2 0x107b5531a in jobs_execution op_execution.c:31
    #3 0x107b554d2 in op_execution op_execution.c:63
    #4 0x107b54100 in execute_node executing_node.c:33
    #5 0x107b56166 in op_separator op_separator.c:17
    #6 0x107b54100 in execute_node executing_node.c:33
    #7 0x107b4c8e4 in shell shell.c:37
    #8 0x107b4c7fb in main main.c:29
```

**Comment by jle-quel** [comment]
```
    #0 0x100324b88 in get_process get_process.c:30
    #1 0x100329d55 in place_status my_wait.c:17
    #2 0x100329e17 in wait_group my_wait.c:38
    #3 0x100329eae in check_child_in_foreground my_wait.c:54
    #4 0x100329ffa in my_wait my_wait.c:83
    #5 0x100325364 in jobs_execution op_execution.c:36
    #6 0x1003254d2 in op_execution op_execution.c:63
    #7 0x100324100 in execute_node executing_node.c:33
    #8 0x1003261e5 in op_ampersand op_ampersand.c:18
    #9 0x100324100 in execute_node executing_node.c:33
    #10 0x100326166 in op_separator op_separator.c:17
    #11 0x100324100 in execute_node executing_node.c:33
    #12 0x10031c8e4 in shell shell.c:37
    #13 0x10031c7fb in main main.c:29
```

**Comment by jle-quel** [comment]
```
#5 0x100325364 in jobs_execution op_execution.c:36
#6 0x1003254d2 in op_execution op_execution.c:63
#7 0x100324100 in execute_node executing_node.c:33
#8 0x1003261e5 in op_ampersand op_ampersand.c:18
#9 0x100324100 in execute_node executing_node.c:33
#10 0x100326166 in op_separator op_separator.c:17
#11 0x100324100 in execute_node executing_node.c:33
#12 0x10031c8e4 in shell shell.c:37
#13 0x10031c7fb in main main.c:29
```

**Comment by jle-quel** [comment]
```
#1 0x100ac7d55 in place_status my_wait.c:17
#2 0x100ac7e17 in wait_group my_wait.c:38
#3 0x100ac7eae in check_child_in_foreground my_wait.c:54
#4 0x100ac7ffa in my_wait my_wait.c:83
#5 0x100ac3364 in jobs_execution op_execution.c:36
#6 0x100ac34d2 in op_execution op_execution.c:63
#7 0x100ac2100 in execute_node executing_node.c:33
#8 0x100ac41e5 in op_ampersand op_ampersand.c:18
#9 0x100ac2100 in execute_node executing_node.c:33
#10 0x100aba8e4 in shell shell.c:37
#11 0x100aba7fb in main main.c:29
```
